onlyBuiltDependencies:
  - "@sentry/cli"
  - esbuild
overrides:
  vite@*: "catalog:"
packageExtensions:
  "@vercel/analytics@*":
    peerDependencies:
      vite: npm:@voidzero-dev/vite-plus-core@latest
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.3
  vite-plus: 0.3.3
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
